import type { ImportRow } from "./validation";

/**
 * Import template for Korean-market tennis racket catalog data.
 *
 * Each row represents a racket model with its specs and Korean market info.
 * Required fields: brand, model
 * All other fields are optional but recommended for complete catalog entries.
 */
export const IMPORT_TEMPLATE_FIELDS = {
  brand: { required: true, description: "Brand name (English)", example: "Wilson" },
  brandKo: { required: false, description: "Brand name (Korean)", example: "윌슨" },
  brandCountry: { required: false, description: "Brand country code", example: "US" },
  model: { required: true, description: "Model name (English)", example: "Blade 98 v8" },
  modelKo: { required: false, description: "Model name (Korean)", example: "블레이드 98 v8" },
  generation: { required: false, description: "Generation/version", example: "v8" },
  segment: { required: false, description: "Player segment", example: "advanced" },
  releaseYear: { required: false, description: "Release year", example: 2023 },
  discontinued: { required: false, description: "Is discontinued?", example: false },
  gripSize: { required: false, description: "Grip size", example: "G2" },
  weightVariant: { required: false, description: "Weight variant label", example: "standard" },
  regionCode: { required: false, description: "Region code (default: KR)", example: "KR" },
  sku: { required: false, description: "Korean market SKU", example: "WR123456" },
  availableInKorea: { required: false, description: "Currently available in Korea", example: true },
  retailPriceKrw: { required: false, description: "Retail price in KRW", example: 289000 },
  headSizeSqIn: { required: false, description: "Head size (sq in)", example: 98 },
  weightG: { required: false, description: "Unstrung weight (g)", example: 305 },
  balanceMm: { required: false, description: "Balance point (mm)", example: 323 },
  swingWeightKgCm2: { required: false, description: "Swing weight (kg·cm²)", example: 327 },
  stiffnessRa: { required: false, description: "Stiffness (RA)", example: 62 },
  lengthMm: { required: false, description: "Length (mm)", example: 686 },
  beamWidthMm: { required: false, description: "Beam width (mm range)", example: "21/21/21" },
  stringPattern: { required: false, description: "String pattern", example: "16x19" },
  composition: { required: false, description: "Frame composition", example: "Braided Graphite & Basalt" },
  sourceUrl: { required: false, description: "Source URL for spec data", example: "https://www.wilson.com/blade-98" },
  sourceType: { required: false, description: "Source type", example: "manufacturer_website" },
} as const;

export const EXAMPLE_IMPORT_ROWS: ImportRow[] = [
  {
    brand: "Wilson",
    brandKo: "윌슨",
    brandCountry: "US",
    model: "Blade 98 16x19 v8",
    modelKo: "블레이드 98 v8",
    generation: "v8",
    segment: "advanced",
    releaseYear: 2023,
    discontinued: false,
    gripSize: "G2",
    weightVariant: "standard",
    regionCode: "KR",
    availableInKorea: true,
    retailPriceKrw: 289000,
    headSizeSqIn: 98,
    weightG: 305,
    balanceMm: 323,
    swingWeightKgCm2: 327,
    stiffnessRa: 62,
    lengthMm: 686,
    beamWidthMm: "21/21/21",
    stringPattern: "16x19",
    composition: "Braided Graphite & Basalt",
    sourceType: "manufacturer_website",
  },
  {
    brand: "Yonex",
    brandKo: "요넥스",
    brandCountry: "JP",
    model: "EZONE 98",
    modelKo: "이존 98",
    generation: "2022",
    segment: "intermediate",
    releaseYear: 2022,
    discontinued: false,
    regionCode: "KR",
    availableInKorea: true,
    retailPriceKrw: 268000,
    headSizeSqIn: 98,
    weightG: 305,
    balanceMm: 315,
    swingWeightKgCm2: 323,
    stiffnessRa: 64,
    lengthMm: 686,
    beamWidthMm: "23.5/26/22",
    stringPattern: "16x19",
    composition: "2G-Namd Flex Force & VDM",
    sourceType: "manufacturer_website",
  },
];
