import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import {
  brands,
  racketModels,
  racketVariants,
  racketSpecs,
  specSources,
} from "./schema";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type RacketSeedRow = {
  brand: string;
  brandKo: string;
  brandCountry: string;
  model: string;
  modelKo: string;
  generation?: string;
  segment: string; // "beginner" | "intermediate" | "advanced" | "pro"
  releaseYear: number;
  discontinued: boolean;
  availableInKorea: boolean;
  retailPriceKrw: number;
  headSizeSqIn: number;
  weightG: number;
  balanceMm: number;
  swingWeightKgCm2: number;
  stiffnessRa: number;
  lengthMm: number;
  beamWidthMm: string;
  stringPattern: string;
  composition: string;
};

// ---------------------------------------------------------------------------
// Data — 80 Korean-market racket records
// ---------------------------------------------------------------------------
// Distribution:
//   Wilson        15
//   Yonex         15
//   Head          13
//   Babolat       13
//   Dunlop        10
//   Prince         7
//   Tecnifibre     7
//                 --
//                 80
//
// Segment mix:
//   beginner      15
//   intermediate  25
//   advanced      25
//   pro           15
//
// Discontinued: 6 entries

export const KOREAN_MARKET_RACKETS: RacketSeedRow[] = [
  // =========================================================================
  // WILSON (15)
  // =========================================================================
  {
    brand: "Wilson",
    brandKo: "윌슨",
    brandCountry: "US",
    model: "Pro Staff RF97 Autograph v13",
    modelKo: "프로 스태프 RF97 오토그래프 v13",
    generation: "v13",
    segment: "pro",
    releaseYear: 2021,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 360000,
    headSizeSqIn: 97,
    weightG: 340,
    balanceMm: 310,
    swingWeightKgCm2: 338,
    stiffnessRa: 60,
    lengthMm: 686,
    beamWidthMm: "21/21/21",
    stringPattern: "16x19",
    composition: "Graphite with Basalt fibers",
  },
  {
    brand: "Wilson",
    brandKo: "윌슨",
    brandCountry: "US",
    model: "Blade 98 v8 16x19",
    modelKo: "블레이드 98 v8 16x19",
    generation: "v8",
    segment: "advanced",
    releaseYear: 2021,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 320000,
    headSizeSqIn: 98,
    weightG: 305,
    balanceMm: 315,
    swingWeightKgCm2: 318,
    stiffnessRa: 62,
    lengthMm: 686,
    beamWidthMm: "21/23/21",
    stringPattern: "16x19",
    composition: "Braided Graphite with Carbon Fiber",
  },
  {
    brand: "Wilson",
    brandKo: "윌슨",
    brandCountry: "US",
    model: "Blade 98 v8 18x20",
    modelKo: "블레이드 98 v8 18x20",
    generation: "v8",
    segment: "pro",
    releaseYear: 2021,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 320000,
    headSizeSqIn: 98,
    weightG: 304,
    balanceMm: 314,
    swingWeightKgCm2: 322,
    stiffnessRa: 62,
    lengthMm: 686,
    beamWidthMm: "21/23/21",
    stringPattern: "18x20",
    composition: "Braided Graphite with Carbon Fiber",
  },
  {
    brand: "Wilson",
    brandKo: "윌슨",
    brandCountry: "US",
    model: "Ultra 100 v4",
    modelKo: "울트라 100 v4",
    generation: "v4",
    segment: "intermediate",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 265000,
    headSizeSqIn: 100,
    weightG: 300,
    balanceMm: 325,
    swingWeightKgCm2: 312,
    stiffnessRa: 68,
    lengthMm: 686,
    beamWidthMm: "23/26/22",
    stringPattern: "16x19",
    composition: "Graphite with PowerHole Technology",
  },
  {
    brand: "Wilson",
    brandKo: "윌슨",
    brandCountry: "US",
    model: "Ultra 108 v4",
    modelKo: "울트라 108 v4",
    generation: "v4",
    segment: "beginner",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 240000,
    headSizeSqIn: 108,
    weightG: 275,
    balanceMm: 335,
    swingWeightKgCm2: 298,
    stiffnessRa: 70,
    lengthMm: 686,
    beamWidthMm: "26/28/24",
    stringPattern: "16x19",
    composition: "Graphite Composite",
  },
  {
    brand: "Wilson",
    brandKo: "윌슨",
    brandCountry: "US",
    model: "Clash 100 v2",
    modelKo: "클래시 100 v2",
    generation: "v2",
    segment: "intermediate",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 310000,
    headSizeSqIn: 100,
    weightG: 295,
    balanceMm: 320,
    swingWeightKgCm2: 310,
    stiffnessRa: 55,
    lengthMm: 686,
    beamWidthMm: "24/27/22",
    stringPattern: "16x19",
    composition: "FreeFlex Carbon + StableSmart Frame Technology",
  },
  {
    brand: "Wilson",
    brandKo: "윌슨",
    brandCountry: "US",
    model: "Clash 100L v2",
    modelKo: "클래시 100L v2",
    generation: "v2",
    segment: "beginner",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 295000,
    headSizeSqIn: 100,
    weightG: 280,
    balanceMm: 328,
    swingWeightKgCm2: 299,
    stiffnessRa: 55,
    lengthMm: 686,
    beamWidthMm: "24/27/22",
    stringPattern: "16x19",
    composition: "FreeFlex Carbon + StableSmart Frame Technology",
  },
  {
    brand: "Wilson",
    brandKo: "윌슨",
    brandCountry: "US",
    model: "Burn 100S v5",
    modelKo: "번 100S v5",
    generation: "v5",
    segment: "intermediate",
    releaseYear: 2020,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 250000,
    headSizeSqIn: 100,
    weightG: 290,
    balanceMm: 324,
    swingWeightKgCm2: 305,
    stiffnessRa: 66,
    lengthMm: 686,
    beamWidthMm: "25/28/22",
    stringPattern: "18x16",
    composition: "Graphite Composite with Spin Effect Technology",
  },
  {
    brand: "Wilson",
    brandKo: "윌슨",
    brandCountry: "US",
    model: "Pro Staff 97L v13",
    modelKo: "프로 스태프 97L v13",
    generation: "v13",
    segment: "advanced",
    releaseYear: 2021,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 330000,
    headSizeSqIn: 97,
    weightG: 290,
    balanceMm: 318,
    swingWeightKgCm2: 308,
    stiffnessRa: 60,
    lengthMm: 686,
    beamWidthMm: "21/21/21",
    stringPattern: "16x19",
    composition: "Graphite with Basalt fibers",
  },
  {
    brand: "Wilson",
    brandKo: "윌슨",
    brandCountry: "US",
    model: "Juice 100S",
    modelKo: "쥬스 100S",
    segment: "beginner",
    releaseYear: 2018,
    discontinued: true,
    availableInKorea: false,
    retailPriceKrw: 195000,
    headSizeSqIn: 100,
    weightG: 285,
    balanceMm: 330,
    swingWeightKgCm2: 300,
    stiffnessRa: 67,
    lengthMm: 686,
    beamWidthMm: "26/28/23",
    stringPattern: "18x16",
    composition: "Graphite Composite",
  },
  {
    brand: "Wilson",
    brandKo: "윌슨",
    brandCountry: "US",
    model: "Shift 99 Pro v1",
    modelKo: "쉬프트 99 프로 v1",
    generation: "v1",
    segment: "advanced",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 345000,
    headSizeSqIn: 99,
    weightG: 310,
    balanceMm: 313,
    swingWeightKgCm2: 324,
    stiffnessRa: 63,
    lengthMm: 686,
    beamWidthMm: "22/24/21",
    stringPattern: "16x19",
    composition: "Carbon Fiber Braid",
  },
  {
    brand: "Wilson",
    brandKo: "윌슨",
    brandCountry: "US",
    model: "Shift 99 v1",
    modelKo: "쉬프트 99 v1",
    generation: "v1",
    segment: "intermediate",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 310000,
    headSizeSqIn: 99,
    weightG: 300,
    balanceMm: 318,
    swingWeightKgCm2: 315,
    stiffnessRa: 63,
    lengthMm: 686,
    beamWidthMm: "22/24/21",
    stringPattern: "16x19",
    composition: "Carbon Fiber Braid",
  },
  {
    brand: "Wilson",
    brandKo: "윌슨",
    brandCountry: "US",
    model: "Ultra Tour 95 v4",
    modelKo: "울트라 투어 95 v4",
    generation: "v4",
    segment: "pro",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 320000,
    headSizeSqIn: 95,
    weightG: 315,
    balanceMm: 310,
    swingWeightKgCm2: 328,
    stiffnessRa: 64,
    lengthMm: 686,
    beamWidthMm: "20/22/20",
    stringPattern: "16x20",
    composition: "Graphite with Aramid Fibers",
  },
  {
    brand: "Wilson",
    brandKo: "윌슨",
    brandCountry: "US",
    model: "Roland Garros Clash 100",
    modelKo: "롤랑가로스 클래시 100",
    segment: "intermediate",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 310000,
    headSizeSqIn: 100,
    weightG: 295,
    balanceMm: 320,
    swingWeightKgCm2: 310,
    stiffnessRa: 55,
    lengthMm: 686,
    beamWidthMm: "24/27/22",
    stringPattern: "16x19",
    composition: "FreeFlex Carbon + StableSmart Frame Technology",
  },
  {
    brand: "Wilson",
    brandKo: "윌슨",
    brandCountry: "US",
    model: "Six One 95 18x20",
    modelKo: "식스원 95 18x20",
    segment: "pro",
    releaseYear: 2019,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 270000,
    headSizeSqIn: 95,
    weightG: 322,
    balanceMm: 308,
    swingWeightKgCm2: 334,
    stiffnessRa: 64,
    lengthMm: 686,
    beamWidthMm: "21/21/21",
    stringPattern: "18x20",
    composition: "Graphite with Aramid Fibers",
  },

  // =========================================================================
  // HEAD (13)
  // =========================================================================
  {
    brand: "Head",
    brandKo: "헤드",
    brandCountry: "AT",
    model: "Speed Pro 2024",
    modelKo: "스피드 프로 2024",
    generation: "2024",
    segment: "pro",
    releaseYear: 2024,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 370000,
    headSizeSqIn: 100,
    weightG: 310,
    balanceMm: 315,
    swingWeightKgCm2: 325,
    stiffnessRa: 63,
    lengthMm: 686,
    beamWidthMm: "23/23/22",
    stringPattern: "16x19",
    composition: "Graphene 360+ with Spiralfibers",
  },
  {
    brand: "Head",
    brandKo: "헤드",
    brandCountry: "AT",
    model: "Speed MP 2024",
    modelKo: "스피드 MP 2024",
    generation: "2024",
    segment: "advanced",
    releaseYear: 2024,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 340000,
    headSizeSqIn: 100,
    weightG: 300,
    balanceMm: 320,
    swingWeightKgCm2: 315,
    stiffnessRa: 63,
    lengthMm: 686,
    beamWidthMm: "23/23/22",
    stringPattern: "16x19",
    composition: "Graphene 360+ with Spiralfibers",
  },
  {
    brand: "Head",
    brandKo: "헤드",
    brandCountry: "AT",
    model: "Prestige Pro 2023",
    modelKo: "프레스티지 프로 2023",
    generation: "2023",
    segment: "pro",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 360000,
    headSizeSqIn: 95,
    weightG: 320,
    balanceMm: 308,
    swingWeightKgCm2: 336,
    stiffnessRa: 61,
    lengthMm: 686,
    beamWidthMm: "20/20/20",
    stringPattern: "18x20",
    composition: "Graphene 360+ Carbon",
  },
  {
    brand: "Head",
    brandKo: "헤드",
    brandCountry: "AT",
    model: "Prestige MP 2023",
    modelKo: "프레스티지 MP 2023",
    generation: "2023",
    segment: "advanced",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 340000,
    headSizeSqIn: 98,
    weightG: 315,
    balanceMm: 310,
    swingWeightKgCm2: 330,
    stiffnessRa: 61,
    lengthMm: 686,
    beamWidthMm: "21/21/20",
    stringPattern: "18x20",
    composition: "Graphene 360+ Carbon",
  },
  {
    brand: "Head",
    brandKo: "헤드",
    brandCountry: "AT",
    model: "Radical MP 2023",
    modelKo: "래디컬 MP 2023",
    generation: "2023",
    segment: "intermediate",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 320000,
    headSizeSqIn: 98,
    weightG: 295,
    balanceMm: 320,
    swingWeightKgCm2: 313,
    stiffnessRa: 66,
    lengthMm: 686,
    beamWidthMm: "22/26/22",
    stringPattern: "16x19",
    composition: "Graphene 360+ with Auxetic",
  },
  {
    brand: "Head",
    brandKo: "헤드",
    brandCountry: "AT",
    model: "Instinct MP 2022",
    modelKo: "인스팅트 MP 2022",
    generation: "2022",
    segment: "intermediate",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 295000,
    headSizeSqIn: 100,
    weightG: 290,
    balanceMm: 323,
    swingWeightKgCm2: 305,
    stiffnessRa: 67,
    lengthMm: 686,
    beamWidthMm: "25/28/22",
    stringPattern: "16x19",
    composition: "Graphene 360+ Carbon",
  },
  {
    brand: "Head",
    brandKo: "헤드",
    brandCountry: "AT",
    model: "Extreme MP 2022",
    modelKo: "익스트림 MP 2022",
    generation: "2022",
    segment: "intermediate",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 285000,
    headSizeSqIn: 100,
    weightG: 295,
    balanceMm: 328,
    swingWeightKgCm2: 312,
    stiffnessRa: 70,
    lengthMm: 686,
    beamWidthMm: "25/28/23",
    stringPattern: "16x19",
    composition: "Graphene 360+ with Extreme Tech",
  },
  {
    brand: "Head",
    brandKo: "헤드",
    brandCountry: "AT",
    model: "MXG 5",
    modelKo: "MXG 5",
    segment: "beginner",
    releaseYear: 2018,
    discontinued: true,
    availableInKorea: false,
    retailPriceKrw: 185000,
    headSizeSqIn: 104,
    weightG: 278,
    balanceMm: 335,
    swingWeightKgCm2: 296,
    stiffnessRa: 68,
    lengthMm: 686,
    beamWidthMm: "26/29/24",
    stringPattern: "16x19",
    composition: "Magnesium Graphite Composite",
  },
  {
    brand: "Head",
    brandKo: "헤드",
    brandCountry: "AT",
    model: "Ti.S6",
    modelKo: "Ti.S6",
    segment: "beginner",
    releaseYear: 2017,
    discontinued: true,
    availableInKorea: false,
    retailPriceKrw: 180000,
    headSizeSqIn: 115,
    weightG: 260,
    balanceMm: 345,
    swingWeightKgCm2: 285,
    stiffnessRa: 71,
    lengthMm: 699,
    beamWidthMm: "28/30/26",
    stringPattern: "16x19",
    composition: "Titanium Composite",
  },
  {
    brand: "Head",
    brandKo: "헤드",
    brandCountry: "AT",
    model: "Boom Pro 2022",
    modelKo: "붐 프로 2022",
    generation: "2022",
    segment: "advanced",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 330000,
    headSizeSqIn: 98,
    weightG: 310,
    balanceMm: 317,
    swingWeightKgCm2: 324,
    stiffnessRa: 62,
    lengthMm: 686,
    beamWidthMm: "21/23/21",
    stringPattern: "16x19",
    composition: "Graphene 360+ with Auxetic Technology",
  },
  {
    brand: "Head",
    brandKo: "헤드",
    brandCountry: "AT",
    model: "Gravity Pro 2023",
    modelKo: "그래비티 프로 2023",
    generation: "2023",
    segment: "advanced",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 345000,
    headSizeSqIn: 100,
    weightG: 315,
    balanceMm: 312,
    swingWeightKgCm2: 328,
    stiffnessRa: 60,
    lengthMm: 686,
    beamWidthMm: "21/23/22",
    stringPattern: "16x20",
    composition: "Graphene 360+ Carbon",
  },
  {
    brand: "Head",
    brandKo: "헤드",
    brandCountry: "AT",
    model: "Gravity MP 2023",
    modelKo: "그래비티 MP 2023",
    generation: "2023",
    segment: "intermediate",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 320000,
    headSizeSqIn: 100,
    weightG: 295,
    balanceMm: 322,
    swingWeightKgCm2: 315,
    stiffnessRa: 60,
    lengthMm: 686,
    beamWidthMm: "21/23/22",
    stringPattern: "16x20",
    composition: "Graphene 360+ Carbon",
  },
  {
    brand: "Head",
    brandKo: "헤드",
    brandCountry: "AT",
    model: "Speed S 2024",
    modelKo: "스피드 S 2024",
    generation: "2024",
    segment: "beginner",
    releaseYear: 2024,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 280000,
    headSizeSqIn: 102,
    weightG: 285,
    balanceMm: 330,
    swingWeightKgCm2: 302,
    stiffnessRa: 63,
    lengthMm: 686,
    beamWidthMm: "25/26/23",
    stringPattern: "16x19",
    composition: "Graphene 360+ with Spiralfibers",
  },

  // =========================================================================
  // BABOLAT (13)
  // =========================================================================
  {
    brand: "Babolat",
    brandKo: "바볼랏",
    brandCountry: "FR",
    model: "Pure Aero 2023",
    modelKo: "퓨어 에어로 2023",
    generation: "2023",
    segment: "advanced",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 340000,
    headSizeSqIn: 100,
    weightG: 300,
    balanceMm: 325,
    swingWeightKgCm2: 318,
    stiffnessRa: 69,
    lengthMm: 686,
    beamWidthMm: "23/26/23",
    stringPattern: "16x19",
    composition: "Carbon Fiber with FSI Technology",
  },
  {
    brand: "Babolat",
    brandKo: "바볼랏",
    brandCountry: "FR",
    model: "Pure Aero Team 2023",
    modelKo: "퓨어 에어로 팀 2023",
    generation: "2023",
    segment: "intermediate",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 295000,
    headSizeSqIn: 100,
    weightG: 285,
    balanceMm: 330,
    swingWeightKgCm2: 305,
    stiffnessRa: 69,
    lengthMm: 686,
    beamWidthMm: "23/26/23",
    stringPattern: "16x19",
    composition: "Carbon Fiber with FSI Technology",
  },
  {
    brand: "Babolat",
    brandKo: "바볼랏",
    brandCountry: "FR",
    model: "Pure Drive 2021",
    modelKo: "퓨어 드라이브 2021",
    generation: "2021",
    segment: "intermediate",
    releaseYear: 2021,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 315000,
    headSizeSqIn: 100,
    weightG: 300,
    balanceMm: 320,
    swingWeightKgCm2: 315,
    stiffnessRa: 71,
    lengthMm: 686,
    beamWidthMm: "25/27/22",
    stringPattern: "16x19",
    composition: "Graphite with HTR System",
  },
  {
    brand: "Babolat",
    brandKo: "바볼랏",
    brandCountry: "FR",
    model: "Pure Drive Team 2021",
    modelKo: "퓨어 드라이브 팀 2021",
    generation: "2021",
    segment: "beginner",
    releaseYear: 2021,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 270000,
    headSizeSqIn: 100,
    weightG: 285,
    balanceMm: 330,
    swingWeightKgCm2: 300,
    stiffnessRa: 71,
    lengthMm: 686,
    beamWidthMm: "25/27/22",
    stringPattern: "16x19",
    composition: "Graphite with HTR System",
  },
  {
    brand: "Babolat",
    brandKo: "바볼랏",
    brandCountry: "FR",
    model: "Pure Strike 97 18x20",
    modelKo: "퓨어 스트라이크 97 18x20",
    segment: "pro",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 350000,
    headSizeSqIn: 97,
    weightG: 320,
    balanceMm: 310,
    swingWeightKgCm2: 332,
    stiffnessRa: 70,
    lengthMm: 686,
    beamWidthMm: "21/21/21",
    stringPattern: "18x20",
    composition: "Carbon Fiber with Cortex System",
  },
  {
    brand: "Babolat",
    brandKo: "바볼랏",
    brandCountry: "FR",
    model: "Pure Strike 100 16x19",
    modelKo: "퓨어 스트라이크 100 16x19",
    segment: "advanced",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 320000,
    headSizeSqIn: 100,
    weightG: 300,
    balanceMm: 315,
    swingWeightKgCm2: 318,
    stiffnessRa: 70,
    lengthMm: 686,
    beamWidthMm: "22/22/21",
    stringPattern: "16x19",
    composition: "Carbon Fiber with Cortex System",
  },
  {
    brand: "Babolat",
    brandKo: "바볼랏",
    brandCountry: "FR",
    model: "Pure Control 97 18x20",
    modelKo: "퓨어 컨트롤 97 18x20",
    segment: "pro",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 360000,
    headSizeSqIn: 97,
    weightG: 315,
    balanceMm: 308,
    swingWeightKgCm2: 330,
    stiffnessRa: 62,
    lengthMm: 686,
    beamWidthMm: "21/21/20",
    stringPattern: "18x20",
    composition: "Carbon Fiber with Cortex Pure Feel",
  },
  {
    brand: "Babolat",
    brandKo: "바볼랏",
    brandCountry: "FR",
    model: "Boost Aero",
    modelKo: "부스트 에어로",
    segment: "beginner",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 185000,
    headSizeSqIn: 105,
    weightG: 270,
    balanceMm: 340,
    swingWeightKgCm2: 291,
    stiffnessRa: 71,
    lengthMm: 686,
    beamWidthMm: "27/29/25",
    stringPattern: "16x19",
    composition: "Graphite Composite",
  },
  {
    brand: "Babolat",
    brandKo: "바볼랏",
    brandCountry: "FR",
    model: "Boost Drive",
    modelKo: "부스트 드라이브",
    segment: "beginner",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 185000,
    headSizeSqIn: 105,
    weightG: 270,
    balanceMm: 340,
    swingWeightKgCm2: 291,
    stiffnessRa: 68,
    lengthMm: 686,
    beamWidthMm: "27/29/25",
    stringPattern: "16x19",
    composition: "Graphite Composite",
  },
  {
    brand: "Babolat",
    brandKo: "바볼랏",
    brandCountry: "FR",
    model: "EVO Aero",
    modelKo: "에보 에어로",
    segment: "beginner",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 215000,
    headSizeSqIn: 102,
    weightG: 275,
    balanceMm: 338,
    swingWeightKgCm2: 296,
    stiffnessRa: 71,
    lengthMm: 686,
    beamWidthMm: "25/28/24",
    stringPattern: "16x19",
    composition: "Graphite Composite",
  },
  {
    brand: "Babolat",
    brandKo: "바볼랏",
    brandCountry: "FR",
    model: "Pure Aero Lite 2023",
    modelKo: "퓨어 에어로 라이트 2023",
    generation: "2023",
    segment: "intermediate",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 275000,
    headSizeSqIn: 100,
    weightG: 270,
    balanceMm: 335,
    swingWeightKgCm2: 293,
    stiffnessRa: 69,
    lengthMm: 686,
    beamWidthMm: "23/26/23",
    stringPattern: "16x19",
    composition: "Carbon Fiber with FSI Technology",
  },
  {
    brand: "Babolat",
    brandKo: "바볼랏",
    brandCountry: "FR",
    model: "Aero G",
    modelKo: "에어로 G",
    segment: "advanced",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 300000,
    headSizeSqIn: 100,
    weightG: 300,
    balanceMm: 330,
    swingWeightKgCm2: 316,
    stiffnessRa: 67,
    lengthMm: 686,
    beamWidthMm: "23/26/22",
    stringPattern: "16x20",
    composition: "Carbon Fiber with GT Technology",
  },
  {
    brand: "Babolat",
    brandKo: "바볼랏",
    brandCountry: "FR",
    model: "Pure Drive 110 2021",
    modelKo: "퓨어 드라이브 110 2021",
    generation: "2021",
    segment: "beginner",
    releaseYear: 2021,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 245000,
    headSizeSqIn: 110,
    weightG: 255,
    balanceMm: 340,
    swingWeightKgCm2: 282,
    stiffnessRa: 68,
    lengthMm: 686,
    beamWidthMm: "27/29/25",
    stringPattern: "16x19",
    composition: "Graphite with HTR System",
  },

  // =========================================================================
  // YONEX (15)
  // =========================================================================
  {
    brand: "Yonex",
    brandKo: "요넥스",
    brandCountry: "JP",
    model: "VCORE Pro 97 2021",
    modelKo: "브이코어 프로 97 2021",
    generation: "2021",
    segment: "pro",
    releaseYear: 2021,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 350000,
    headSizeSqIn: 97,
    weightG: 310,
    balanceMm: 315,
    swingWeightKgCm2: 326,
    stiffnessRa: 62,
    lengthMm: 686,
    beamWidthMm: "21/21/21",
    stringPattern: "16x19",
    composition: "M40X Carbon with Vibration Dampening Mesh",
  },
  {
    brand: "Yonex",
    brandKo: "요넥스",
    brandCountry: "JP",
    model: "VCORE 98 2023",
    modelKo: "브이코어 98 2023",
    generation: "2023",
    segment: "advanced",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 330000,
    headSizeSqIn: 98,
    weightG: 305,
    balanceMm: 320,
    swingWeightKgCm2: 320,
    stiffnessRa: 66,
    lengthMm: 686,
    beamWidthMm: "22/22/21",
    stringPattern: "16x19",
    composition: "Graphite with VDM and CIL Technology",
  },
  {
    brand: "Yonex",
    brandKo: "요넥스",
    brandCountry: "JP",
    model: "VCORE 100 2023",
    modelKo: "브이코어 100 2023",
    generation: "2023",
    segment: "intermediate",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 295000,
    headSizeSqIn: 100,
    weightG: 300,
    balanceMm: 325,
    swingWeightKgCm2: 313,
    stiffnessRa: 66,
    lengthMm: 686,
    beamWidthMm: "23/23/22",
    stringPattern: "16x19",
    composition: "Graphite with VDM Technology",
  },
  {
    brand: "Yonex",
    brandKo: "요넥스",
    brandCountry: "JP",
    model: "VCORE 100L 2023",
    modelKo: "브이코어 100L 2023",
    generation: "2023",
    segment: "beginner",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 265000,
    headSizeSqIn: 100,
    weightG: 280,
    balanceMm: 335,
    swingWeightKgCm2: 298,
    stiffnessRa: 66,
    lengthMm: 686,
    beamWidthMm: "23/23/22",
    stringPattern: "16x19",
    composition: "Graphite with VDM Technology",
  },
  {
    brand: "Yonex",
    brandKo: "요넥스",
    brandCountry: "JP",
    model: "Ezone 98 2022",
    modelKo: "이존 98 2022",
    generation: "2022",
    segment: "intermediate",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 320000,
    headSizeSqIn: 98,
    weightG: 305,
    balanceMm: 320,
    swingWeightKgCm2: 318,
    stiffnessRa: 65,
    lengthMm: 686,
    beamWidthMm: "23/23/22",
    stringPattern: "16x19",
    composition: "Graphite with Isometric Design and HM Graphite",
  },
  {
    brand: "Yonex",
    brandKo: "요넥스",
    brandCountry: "JP",
    model: "Ezone 100 2022",
    modelKo: "이존 100 2022",
    generation: "2022",
    segment: "beginner",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 285000,
    headSizeSqIn: 100,
    weightG: 300,
    balanceMm: 328,
    swingWeightKgCm2: 308,
    stiffnessRa: 65,
    lengthMm: 686,
    beamWidthMm: "23/25/23",
    stringPattern: "16x19",
    composition: "Graphite with Isometric Design and HM Graphite",
  },
  {
    brand: "Yonex",
    brandKo: "요넥스",
    brandCountry: "JP",
    model: "Percept 97 2023",
    modelKo: "퍼셉트 97 2023",
    generation: "2023",
    segment: "advanced",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 345000,
    headSizeSqIn: 97,
    weightG: 310,
    balanceMm: 314,
    swingWeightKgCm2: 322,
    stiffnessRa: 61,
    lengthMm: 686,
    beamWidthMm: "21/21/21",
    stringPattern: "16x19",
    composition: "M40X Carbon Fiber",
  },
  {
    brand: "Yonex",
    brandKo: "요넥스",
    brandCountry: "JP",
    model: "Percept 100 2023",
    modelKo: "퍼셉트 100 2023",
    generation: "2023",
    segment: "intermediate",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 320000,
    headSizeSqIn: 100,
    weightG: 300,
    balanceMm: 320,
    swingWeightKgCm2: 313,
    stiffnessRa: 61,
    lengthMm: 686,
    beamWidthMm: "22/22/21",
    stringPattern: "16x19",
    composition: "M40X Carbon Fiber",
  },
  {
    brand: "Yonex",
    brandKo: "요넥스",
    brandCountry: "JP",
    model: "VCORE Pro 100 2021",
    modelKo: "브이코어 프로 100 2021",
    generation: "2021",
    segment: "advanced",
    releaseYear: 2021,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 320000,
    headSizeSqIn: 100,
    weightG: 305,
    balanceMm: 317,
    swingWeightKgCm2: 320,
    stiffnessRa: 62,
    lengthMm: 686,
    beamWidthMm: "21/21/21",
    stringPattern: "16x19",
    composition: "M40X Carbon with Vibration Dampening Mesh",
  },
  {
    brand: "Yonex",
    brandKo: "요넥스",
    brandCountry: "JP",
    model: "SV 95i",
    modelKo: "SV 95i",
    segment: "pro",
    releaseYear: 2017,
    discontinued: true,
    availableInKorea: false,
    retailPriceKrw: 215000,
    headSizeSqIn: 95,
    weightG: 325,
    balanceMm: 308,
    swingWeightKgCm2: 334,
    stiffnessRa: 62,
    lengthMm: 686,
    beamWidthMm: "21/21/21",
    stringPattern: "16x19",
    composition: "Graphite Composite",
  },
  {
    brand: "Yonex",
    brandKo: "요넥스",
    brandCountry: "JP",
    model: "VCORE 110 2023",
    modelKo: "브이코어 110 2023",
    generation: "2023",
    segment: "beginner",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 250000,
    headSizeSqIn: 110,
    weightG: 260,
    balanceMm: 343,
    swingWeightKgCm2: 281,
    stiffnessRa: 67,
    lengthMm: 686,
    beamWidthMm: "27/29/25",
    stringPattern: "16x19",
    composition: "Graphite with VDM Technology",
  },
  {
    brand: "Yonex",
    brandKo: "요넥스",
    brandCountry: "JP",
    model: "Ezone 98L 2022",
    modelKo: "이존 98L 2022",
    generation: "2022",
    segment: "intermediate",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 295000,
    headSizeSqIn: 98,
    weightG: 285,
    balanceMm: 330,
    swingWeightKgCm2: 302,
    stiffnessRa: 65,
    lengthMm: 686,
    beamWidthMm: "23/23/22",
    stringPattern: "16x19",
    composition: "Graphite with Isometric Design",
  },
  {
    brand: "Yonex",
    brandKo: "요넥스",
    brandCountry: "JP",
    model: "Percept 97D 2023",
    modelKo: "퍼셉트 97D 2023",
    generation: "2023",
    segment: "pro",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 360000,
    headSizeSqIn: 97,
    weightG: 320,
    balanceMm: 310,
    swingWeightKgCm2: 333,
    stiffnessRa: 61,
    lengthMm: 686,
    beamWidthMm: "21/21/21",
    stringPattern: "18x20",
    composition: "M40X Carbon Fiber",
  },
  {
    brand: "Yonex",
    brandKo: "요넥스",
    brandCountry: "JP",
    model: "VCORE Ace 2023",
    modelKo: "브이코어 에이스 2023",
    generation: "2023",
    segment: "beginner",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 235000,
    headSizeSqIn: 102,
    weightG: 270,
    balanceMm: 340,
    swingWeightKgCm2: 290,
    stiffnessRa: 68,
    lengthMm: 686,
    beamWidthMm: "25/27/23",
    stringPattern: "16x19",
    composition: "Graphite Composite",
  },
  {
    brand: "Yonex",
    brandKo: "요넥스",
    brandCountry: "JP",
    model: "Ezone 100SL 2022",
    modelKo: "이존 100SL 2022",
    generation: "2022",
    segment: "beginner",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 255000,
    headSizeSqIn: 100,
    weightG: 265,
    balanceMm: 342,
    swingWeightKgCm2: 280,
    stiffnessRa: 65,
    lengthMm: 686,
    beamWidthMm: "23/25/23",
    stringPattern: "16x19",
    composition: "Graphite with Isometric Design",
  },

  // =========================================================================
  // DUNLOP (10)
  // =========================================================================
  {
    brand: "Dunlop",
    brandKo: "던롭",
    brandCountry: "GB",
    model: "CX 200 2021",
    modelKo: "CX 200 2021",
    generation: "2021",
    segment: "advanced",
    releaseYear: 2021,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 295000,
    headSizeSqIn: 98,
    weightG: 305,
    balanceMm: 315,
    swingWeightKgCm2: 319,
    stiffnessRa: 65,
    lengthMm: 686,
    beamWidthMm: "21/21/21",
    stringPattern: "16x19",
    composition: "Graphite with Sonic Core Technology",
  },
  {
    brand: "Dunlop",
    brandKo: "던롭",
    brandCountry: "GB",
    model: "CX 200 Tour 18x20 2021",
    modelKo: "CX 200 투어 18x20 2021",
    generation: "2021",
    segment: "pro",
    releaseYear: 2021,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 320000,
    headSizeSqIn: 98,
    weightG: 315,
    balanceMm: 310,
    swingWeightKgCm2: 330,
    stiffnessRa: 65,
    lengthMm: 686,
    beamWidthMm: "20/21/21",
    stringPattern: "18x20",
    composition: "Graphite with Sonic Core Technology",
  },
  {
    brand: "Dunlop",
    brandKo: "던롭",
    brandCountry: "GB",
    model: "CX 400 Tour 2021",
    modelKo: "CX 400 투어 2021",
    generation: "2021",
    segment: "intermediate",
    releaseYear: 2021,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 265000,
    headSizeSqIn: 100,
    weightG: 295,
    balanceMm: 325,
    swingWeightKgCm2: 310,
    stiffnessRa: 67,
    lengthMm: 686,
    beamWidthMm: "23/25/22",
    stringPattern: "16x19",
    composition: "Graphite with Sonic Core Technology",
  },
  {
    brand: "Dunlop",
    brandKo: "던롭",
    brandCountry: "GB",
    model: "SX 300 2022",
    modelKo: "SX 300 2022",
    generation: "2022",
    segment: "advanced",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 280000,
    headSizeSqIn: 100,
    weightG: 300,
    balanceMm: 330,
    swingWeightKgCm2: 316,
    stiffnessRa: 72,
    lengthMm: 686,
    beamWidthMm: "25/28/23",
    stringPattern: "16x20",
    composition: "Graphite with Flex Force Technology",
  },
  {
    brand: "Dunlop",
    brandKo: "던롭",
    brandCountry: "GB",
    model: "SX 300 Lite 2022",
    modelKo: "SX 300 라이트 2022",
    generation: "2022",
    segment: "beginner",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 245000,
    headSizeSqIn: 100,
    weightG: 280,
    balanceMm: 338,
    swingWeightKgCm2: 300,
    stiffnessRa: 70,
    lengthMm: 686,
    beamWidthMm: "25/28/23",
    stringPattern: "16x19",
    composition: "Graphite with Flex Force Technology",
  },
  {
    brand: "Dunlop",
    brandKo: "던롭",
    brandCountry: "GB",
    model: "FX 500 2023",
    modelKo: "FX 500 2023",
    generation: "2023",
    segment: "intermediate",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 270000,
    headSizeSqIn: 100,
    weightG: 295,
    balanceMm: 325,
    swingWeightKgCm2: 308,
    stiffnessRa: 67,
    lengthMm: 686,
    beamWidthMm: "24/26/22",
    stringPattern: "16x19",
    composition: "Graphite with Sonic Core and Power Bridge",
  },
  {
    brand: "Dunlop",
    brandKo: "던롭",
    brandCountry: "GB",
    model: "FX 500 Tour 2023",
    modelKo: "FX 500 투어 2023",
    generation: "2023",
    segment: "advanced",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 290000,
    headSizeSqIn: 98,
    weightG: 305,
    balanceMm: 316,
    swingWeightKgCm2: 319,
    stiffnessRa: 65,
    lengthMm: 686,
    beamWidthMm: "22/24/22",
    stringPattern: "16x19",
    composition: "Graphite with Sonic Core and Power Bridge",
  },
  {
    brand: "Dunlop",
    brandKo: "던롭",
    brandCountry: "GB",
    model: "CX Pro 255 2021",
    modelKo: "CX 프로 255 2021",
    generation: "2021",
    segment: "intermediate",
    releaseYear: 2021,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 260000,
    headSizeSqIn: 100,
    weightG: 255,
    balanceMm: 338,
    swingWeightKgCm2: 294,
    stiffnessRa: 63,
    lengthMm: 686,
    beamWidthMm: "21/23/22",
    stringPattern: "16x19",
    composition: "Graphite with Sonic Core Technology",
  },
  {
    brand: "Dunlop",
    brandKo: "던롭",
    brandCountry: "GB",
    model: "SX 300 Tour 2022",
    modelKo: "SX 300 투어 2022",
    generation: "2022",
    segment: "pro",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 310000,
    headSizeSqIn: 97,
    weightG: 310,
    balanceMm: 315,
    swingWeightKgCm2: 325,
    stiffnessRa: 71,
    lengthMm: 686,
    beamWidthMm: "23/26/22",
    stringPattern: "16x20",
    composition: "Graphite with Flex Force Technology",
  },
  {
    brand: "Dunlop",
    brandKo: "던롭",
    brandCountry: "GB",
    model: "Biomimetic 500",
    modelKo: "바이오미메틱 500",
    segment: "intermediate",
    releaseYear: 2015,
    discontinued: true,
    availableInKorea: false,
    retailPriceKrw: 195000,
    headSizeSqIn: 98,
    weightG: 300,
    balanceMm: 315,
    swingWeightKgCm2: 315,
    stiffnessRa: 66,
    lengthMm: 686,
    beamWidthMm: "21/23/21",
    stringPattern: "16x19",
    composition: "Graphite with HM6 Carbon",
  },

  // =========================================================================
  // PRINCE (7)
  // =========================================================================
  {
    brand: "Prince",
    brandKo: "프린스",
    brandCountry: "US",
    model: "Textreme Tour 100P",
    modelKo: "텍스트림 투어 100P",
    segment: "pro",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 320000,
    headSizeSqIn: 100,
    weightG: 315,
    balanceMm: 310,
    swingWeightKgCm2: 328,
    stiffnessRa: 60,
    lengthMm: 686,
    beamWidthMm: "21/23/21",
    stringPattern: "16x18",
    composition: "TeXtreme Graphite Weave",
  },
  {
    brand: "Prince",
    brandKo: "프린스",
    brandCountry: "US",
    model: "Textreme Tour 98",
    modelKo: "텍스트림 투어 98",
    segment: "advanced",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 305000,
    headSizeSqIn: 98,
    weightG: 310,
    balanceMm: 313,
    swingWeightKgCm2: 325,
    stiffnessRa: 59,
    lengthMm: 686,
    beamWidthMm: "21/22/21",
    stringPattern: "16x18",
    composition: "TeXtreme Graphite Weave",
  },
  {
    brand: "Prince",
    brandKo: "프린스",
    brandCountry: "US",
    model: "Beast 100",
    modelKo: "비스트 100",
    segment: "intermediate",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 275000,
    headSizeSqIn: 100,
    weightG: 295,
    balanceMm: 328,
    swingWeightKgCm2: 309,
    stiffnessRa: 65,
    lengthMm: 686,
    beamWidthMm: "23/26/22",
    stringPattern: "16x19",
    composition: "Graphite with ATS Technology",
  },
  {
    brand: "Prince",
    brandKo: "프린스",
    brandCountry: "US",
    model: "Phantom 100P 18x20",
    modelKo: "팬텀 100P 18x20",
    segment: "advanced",
    releaseYear: 2021,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 295000,
    headSizeSqIn: 100,
    weightG: 320,
    balanceMm: 307,
    swingWeightKgCm2: 330,
    stiffnessRa: 58,
    lengthMm: 686,
    beamWidthMm: "21/21/21",
    stringPattern: "18x20",
    composition: "Graphite with LongBody Technology",
  },
  {
    brand: "Prince",
    brandKo: "프린스",
    brandCountry: "US",
    model: "Spectrum 105",
    modelKo: "스펙트럼 105",
    segment: "beginner",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 210000,
    headSizeSqIn: 105,
    weightG: 275,
    balanceMm: 338,
    swingWeightKgCm2: 297,
    stiffnessRa: 68,
    lengthMm: 686,
    beamWidthMm: "26/28/24",
    stringPattern: "16x19",
    composition: "Graphite Composite",
  },
  {
    brand: "Prince",
    brandKo: "프린스",
    brandCountry: "US",
    model: "Ripcord 100",
    modelKo: "립코드 100",
    segment: "intermediate",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 250000,
    headSizeSqIn: 100,
    weightG: 290,
    balanceMm: 324,
    swingWeightKgCm2: 305,
    stiffnessRa: 70,
    lengthMm: 686,
    beamWidthMm: "24/26/23",
    stringPattern: "16x19",
    composition: "Graphite with ATS Technology",
  },
  {
    brand: "Prince",
    brandKo: "프린스",
    brandCountry: "US",
    model: "Warrior 107",
    modelKo: "워리어 107",
    segment: "beginner",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 195000,
    headSizeSqIn: 107,
    weightG: 268,
    balanceMm: 342,
    swingWeightKgCm2: 285,
    stiffnessRa: 70,
    lengthMm: 686,
    beamWidthMm: "27/29/25",
    stringPattern: "16x19",
    composition: "Graphite Composite",
  },

  // =========================================================================
  // TECNIFIBRE (7)
  // =========================================================================
  {
    brand: "Tecnifibre",
    brandKo: "테크니파이버",
    brandCountry: "FR",
    model: "TF40 305 18x20",
    modelKo: "TF40 305 18x20",
    segment: "pro",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 355000,
    headSizeSqIn: 98,
    weightG: 305,
    balanceMm: 308,
    swingWeightKgCm2: 318,
    stiffnessRa: 60,
    lengthMm: 686,
    beamWidthMm: "21/21/20",
    stringPattern: "18x20",
    composition: "Carbon Fiber with Thermocore Technology",
  },
  {
    brand: "Tecnifibre",
    brandKo: "테크니파이버",
    brandCountry: "FR",
    model: "TF40 315 16x19",
    modelKo: "TF40 315 16x19",
    segment: "advanced",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 340000,
    headSizeSqIn: 98,
    weightG: 315,
    balanceMm: 310,
    swingWeightKgCm2: 328,
    stiffnessRa: 60,
    lengthMm: 686,
    beamWidthMm: "21/21/20",
    stringPattern: "16x19",
    composition: "Carbon Fiber with Thermocore Technology",
  },
  {
    brand: "Tecnifibre",
    brandKo: "테크니파이버",
    brandCountry: "FR",
    model: "TFight 300 Isoflex 2023",
    modelKo: "TF파이트 300 아이소플렉스 2023",
    generation: "2023",
    segment: "advanced",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 325000,
    headSizeSqIn: 98,
    weightG: 300,
    balanceMm: 316,
    swingWeightKgCm2: 315,
    stiffnessRa: 59,
    lengthMm: 686,
    beamWidthMm: "21/23/21",
    stringPattern: "16x19",
    composition: "Carbon Fiber with Isoflex Technology",
  },
  {
    brand: "Tecnifibre",
    brandKo: "테크니파이버",
    brandCountry: "FR",
    model: "TFight 295 Isoflex 2023",
    modelKo: "TF파이트 295 아이소플렉스 2023",
    generation: "2023",
    segment: "intermediate",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 295000,
    headSizeSqIn: 100,
    weightG: 295,
    balanceMm: 320,
    swingWeightKgCm2: 308,
    stiffnessRa: 59,
    lengthMm: 686,
    beamWidthMm: "22/24/22",
    stringPattern: "16x19",
    composition: "Carbon Fiber with Isoflex Technology",
  },
  {
    brand: "Tecnifibre",
    brandKo: "테크니파이버",
    brandCountry: "FR",
    model: "TFight 265 Isoflex 2023",
    modelKo: "TF파이트 265 아이소플렉스 2023",
    generation: "2023",
    segment: "intermediate",
    releaseYear: 2023,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 270000,
    headSizeSqIn: 100,
    weightG: 265,
    balanceMm: 332,
    swingWeightKgCm2: 293,
    stiffnessRa: 57,
    lengthMm: 686,
    beamWidthMm: "22/24/22",
    stringPattern: "16x19",
    composition: "Carbon Fiber with Isoflex Technology",
  },
  {
    brand: "Tecnifibre",
    brandKo: "테크니파이버",
    brandCountry: "FR",
    model: "Tempo 298 IGA",
    modelKo: "템포 298 IGA",
    segment: "beginner",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 235000,
    headSizeSqIn: 102,
    weightG: 298,
    balanceMm: 330,
    swingWeightKgCm2: 310,
    stiffnessRa: 63,
    lengthMm: 686,
    beamWidthMm: "25/27/23",
    stringPattern: "16x19",
    composition: "Graphite Composite with Innegra",
  },
  {
    brand: "Tecnifibre",
    brandKo: "테크니파이버",
    brandCountry: "FR",
    model: "T-Rebound 298 IGA",
    modelKo: "T-리바운드 298 IGA",
    segment: "beginner",
    releaseYear: 2022,
    discontinued: false,
    availableInKorea: true,
    retailPriceKrw: 215000,
    headSizeSqIn: 104,
    weightG: 280,
    balanceMm: 338,
    swingWeightKgCm2: 298,
    stiffnessRa: 65,
    lengthMm: 686,
    beamWidthMm: "26/28/24",
    stringPattern: "16x19",
    composition: "Graphite Composite with Innegra",
  },
];

// ---------------------------------------------------------------------------
// Seed function
// ---------------------------------------------------------------------------

export async function seedRackets(): Promise<void> {
  const client = postgres(process.env.DATABASE_URL!);
  const db = drizzle(client);

  console.log(`Starting racket seed — ${KOREAN_MARKET_RACKETS.length} records`);

  // -------------------------------------------------------------------------
  // Step 1: Ensure all brands exist
  // -------------------------------------------------------------------------
  const uniqueBrands = Array.from(
    new Map(
      KOREAN_MARKET_RACKETS.map((r) => [
        r.brand,
        { name: r.brand, nameKo: r.brandKo, country: r.brandCountry },
      ])
    ).values()
  );

  console.log(`Upserting ${uniqueBrands.length} brands...`);
  await db.insert(brands).values(uniqueBrands).onConflictDoNothing();

  // Fetch brand id map
  const brandRows = await db.select().from(brands);
  const brandIdMap = new Map(brandRows.map((b) => [b.name, b.id]));

  // -------------------------------------------------------------------------
  // Step 2: Insert each racket
  // -------------------------------------------------------------------------
  let processed = 0;

  for (const row of KOREAN_MARKET_RACKETS) {
    const brandId = brandIdMap.get(row.brand);
    if (!brandId) {
      console.warn(`  WARN: brand not found in DB for row: ${row.brand}`);
      continue;
    }

    // -- 2a. Create racket model
    const [model] = await db
      .insert(racketModels)
      .values({
        brandId,
        name: row.model,
        nameKo: row.modelKo,
        generation: row.generation ?? null,
        segment: row.segment,
        releaseYear: row.releaseYear,
        discontinued: row.discontinued,
      })
      .returning();

    // -- 2b. Create default variant (G2 grip, standard weight, KR region)
    await db.insert(racketVariants).values({
      racketModelId: model.id,
      gripSize: "G2",
      weightVariant: "standard",
      regionCode: "KR",
      availableInKorea: row.availableInKorea,
      retailPriceKrw: row.retailPriceKrw,
    });

    // -- 2c. Create specs (raw state)
    const [specs] = await db
      .insert(racketSpecs)
      .values({
        racketModelId: model.id,
        headSizeSqIn: String(row.headSizeSqIn),
        weightG: String(row.weightG),
        balanceMm: String(row.balanceMm),
        swingWeightKgCm2: String(row.swingWeightKgCm2),
        stiffnessRa: String(row.stiffnessRa),
        lengthMm: String(row.lengthMm),
        beamWidthMm: row.beamWidthMm,
        stringPattern: row.stringPattern,
        composition: row.composition,
        ingestionState: "raw",
      })
      .returning();

    // -- 2d. Create spec source record
    await db.insert(specSources).values({
      racketSpecsId: specs.id,
      sourceType: "seed_data",
      rawValues: {
        brand: row.brand,
        model: row.model,
        generation: row.generation ?? null,
        segment: row.segment,
        releaseYear: row.releaseYear,
        headSizeSqIn: row.headSizeSqIn,
        weightG: row.weightG,
        balanceMm: row.balanceMm,
        swingWeightKgCm2: row.swingWeightKgCm2,
        stiffnessRa: row.stiffnessRa,
        lengthMm: row.lengthMm,
        beamWidthMm: row.beamWidthMm,
        stringPattern: row.stringPattern,
        composition: row.composition,
      },
      confidence: "0.85",
      verifiedByAdmin: false,
    });

    processed += 1;
    if (processed % 10 === 0) {
      console.log(`  Progress: ${processed} / ${KOREAN_MARKET_RACKETS.length} records inserted`);
    }
  }

  console.log(`Seed complete. Inserted ${processed} racket records.`);
  await client.end();
}

// ---------------------------------------------------------------------------
// Main block — allows running directly with:
//   tsx src/db/seed-rackets.ts
// ---------------------------------------------------------------------------
if (
  process.argv[1] &&
  (process.argv[1].endsWith("seed-rackets.ts") ||
    process.argv[1].endsWith("seed-rackets.js"))
) {
  seedRackets().catch((err) => {
    console.error("Racket seed failed:", err);
    process.exit(1);
  });
}
