// This file is generated by scripts/generate-racket-customizer-masks.ts.
// Do not edit it by hand.

export type RacketCustomizerProfile = {
  readonly slug: string;
  readonly productCode: string;
  readonly sourceLayout: "tw-front-side-v1";
  readonly intrinsicWidth: number;
  readonly intrinsicHeight: number;
  readonly stringMaskUrl: string;
  readonly gripMaskUrl: string;
};

export const RACKET_CUSTOMIZER_PROFILES = [
  {
    slug: "babolat-pure-aero-2026",
    productCode: "BPAR26",
    sourceLayout: "tw-front-side-v1",
    intrinsicWidth: 500,
    intrinsicHeight: 858,
    stringMaskUrl: "/images/racket-customizer/babolat-pure-aero-2026-strings.svg",
    gripMaskUrl: "/images/racket-customizer/babolat-pure-aero-2026-grip.svg",
  },
  {
    slug: "head-gravity-mp-2025",
    productCode: "HGMPG",
    sourceLayout: "tw-front-side-v1",
    intrinsicWidth: 500,
    intrinsicHeight: 857,
    stringMaskUrl: "/images/racket-customizer/head-gravity-mp-2025-strings.svg",
    gripMaskUrl: "/images/racket-customizer/head-gravity-mp-2025-grip.svg",
  },
  {
    slug: "yonex-ezone-100-2025",
    productCode: "EZ10BB",
    sourceLayout: "tw-front-side-v1",
    intrinsicWidth: 500,
    intrinsicHeight: 857,
    stringMaskUrl: "/images/racket-customizer/yonex-ezone-100-2025-strings.svg",
    gripMaskUrl: "/images/racket-customizer/yonex-ezone-100-2025-grip.svg",
  },
] as const satisfies readonly RacketCustomizerProfile[];
